name: Build and deploy AzSecPodcast to Azure Web App

on:
  push:
    branches:
      - master
      
jobs:          
  deploy:
    runs-on: windows-latest
    steps:
      - name: Download artifacts from build job
        uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_APP_ID }}",
              "clientSecret":  "${{ secrets.AZURE_PASSWORD }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: 'Deploy to Azure Web App'
        id: deploy-to-azsecpod
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'azsecuritypodcast'
          package: '.'

      - name: logout
        run: |
          az logout
